# Generated by Django 4.2.20 on 2025-03-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], max_length=16),
        ),
        migrations.AlterField(
            model_name='playerskill',
            name='skill',
            field=models.CharField(choices=[('defense', 'Defense'), ('attack', 'Attack'), ('speed', 'Speed'), ('strength', 'Strength'), ('stamina', 'Stamina')], max_length=16),
        ),
    ]
