# Generated by Django 4.2.20 on 2025-03-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_player_position_alter_playerskill_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], max_length=20),
        ),
        migrations.AlterField(
            model_name='playerskill',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_skills', to='my_app.player'),
        ),
        migrations.AlterField(
            model_name='playerskill',
            name='skill',
            field=models.CharField(choices=[('defense', 'Defense'), ('attack', 'Attack'), ('speed', 'Speed'), ('strength', 'Strength'), ('stamina', 'Stamina')], max_length=20),
        ),
    ]
